{% set name = "pypdf2" %}
{% set camelName = "PyPDF2" %}
{% set version = "1.26.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ camelName }}-{{ version }}.tar.gz
  sha256: e28f902f2f0a1603ea95ebe21dff311ef09be3d0f0ef29a3e44a932729564385

build:

  number: 0
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - PyPDF2

about:
  home: http://mstamy2.github.com/PyPDF2
  license: BSD 3-Clause
  summary: 'PDF toolkit'

extra:
  recipe-maintainers:
    - pmlandwehr
