{% set name = "PyPDF2" %}
{% set version = "1.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 20fb6795712e9d1ea73ae61a3e3c4c9580c051a31a6b9961dfb55445c6ce5d6a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - PyPDF2

about:
  home: http://mstamy2.github.com/PyPDF2
  license: BSD-3-Clause
  # LICENSE not in MANIFEST.in - see https://github.com/mstamy2/PyPDF2/pull/288
  license_file: LICENSE
  license_family: BSD
  summary: A utility to read and write PDFs with Python
  doc_url: http://pybrary.net/pyPdf/pythondoc-pyPdf.pdf.html
  dev_url: https://github.com/mstamy2/PyPDF2/

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
