{% set name = "PyPDF2" %}
{% set version = "2.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad40bf56bad7ee9c8adb1de6a4a160a8f2c1b442369ad817584106fb5bde64eb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7

test:
  imports:
    - PyPDF2

about:
  home: http://py-pdf.github.io/PyPDF2/
  license: BSD-3-Clause  # unsure about this license...to be rechecked
  license_file: LICENSE
  license_family: BSD
  summary: A utility to read and write PDFs with Python
  doc_url: https://pypdf2.readthedocs.io/
  dev_url: https://github.com/py-pdf/PyPDF2

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
