travis:
  secure:
    BINSTAR_TOKEN: kifRi3PQnOCJch8+eftG0y2B6/GQO5p/xqKL7hLennvCN9Hg2nTneOqIMkg0iM7rgCHJXhG9zkztsGQabtoeM6/IDY7/KNNUkKX3iLcWg3GFUkjpSaCGCFU6cc186zecNIkaRzOA/w5TnDzxcxWPOnamnBQi7IwjJRFJSipzEjd+ivKn9vkIThtsrlRd9vTwaT+tY39/BCtzCw/3FtaljqTPPKl3wrupFJC3KuMQTXTDObkLpXN4kBEdQfqHLM2aJe7r8bpCwPLYzqPYWevzThMDE5MIYcgcl4U55gDNbC+eUDxpjP/Z3ZnYftFhKg/k+qP8qCAf1Er11HVoQm4qLGDoKNaHqUYBcyzOAL1lUQGxhmp6qAG5DRNyGS6xrFDaG/V1qib0ciPh+Ng9Y/6FierFRGOYMUduEy9GMkRGtH7XquzrOy9GSGrhwyi8Ga0lwJsLB6xNqzer47ps/+BXqCmkkdBOY3oEmDGjkVc4qLA0zigk0/ao62Kj8Pt6yt4D2jiYdWD/ZbbepCJMsZbMfeqvaI1064ceSO9VoZlAq8QpzIEUCR+kAQJs5PadQlGiEL7nVsXGix5CG4MoDNRTFaol2+5RxuEYqVvVA1MOjVd02b/iyYpopasOCzaPuk2cbbnTJ45DYp7hJVwgbTVIbOeLKvOUPoHTmF6UlIn11zk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
